trigger:
- master

#pool:
  #vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  dotnetSdkVersion: '6.x'



# do this before your build tasks
steps:

- task: NuGetAuthenticate@0
  inputs:
    nuGetServiceConnections: 'MyGet feed'

- task: NuGetToolInstaller@1

#build app
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'dotnet build $(buildConfiguration)'

- task: UseDotNet@2
  displayName: 'Use .NET SDK $(dotnetSdkVersion)'
  inputs:
    version: '$(dotnetSdkVersion)'


#test
- task: DotNetCoreCLI@2
  displayName: 'Run unit tests - $(buildConfiguration)'
  inputs:
    command: 'test'
    arguments: '--no-build --configuration $(buildConfiguration)'
    publishTestResults: true
    #projects: '**/*.Tests.csproj'


#pack and restore
- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'off'
    nugetConfigPath: 'nuget.config'
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    feedsToUse: 'select'
    vstsFeed: 'FabVeg/pipelines-dotnet-core'
    includeNuGetOrg: false
    restoreSolution: '**/*.sln'